In [5]:
import numpy as np
import os

directory = "BiLSTM_pred_np_6_summer"
cnt = 0
for filename in os.listdir(os.path.join(os.getcwd(), directory)):
#     print('hk')
    if cnt == 0:
#         print('in')
        loaded_np = np.load('BiLSTM_pred_np_6_summer/' + filename)
        loaded_np = np.reshape(loaded_np, (1, loaded_np.shape[0], loaded_np.shape[1]))
        cnt += 1
    else:
        big_np = np.load('BiLSTM_pred_np_6_summer/' + filename)
        big_np = np.reshape(big_np, (1, big_np.shape[0], big_np.shape[1]))


        # 12 x 8713 x 24 
        #concat
        loaded_np = np.concatenate((loaded_np, big_np), axis=0)
#         loaded_np = np.hstack((loaded_np, big_np))

        print(cnt)
        cnt += 1

    

1
2
3
4
5
6
7
8
9
10
11


In [6]:
print(loaded_np.shape)

(12, 2155, 6)


In [7]:
average_pred = np.mean(loaded_np, axis=0)
print(average_pred.shape)
print(average_pred)

(2155, 6)
[[55.40956608 57.86750285 59.15631644 63.58673986 66.31369019 68.65134939]
 [54.52551444 59.04505253 60.5936842  65.08534749 67.99182097 68.23976835]
 [57.5034097  59.50184663 60.73731391 66.05926959 68.25302633 71.1738294 ]
 ...
 [ 4.04481173 -5.35818879 -2.75764428 -2.00630081  4.67400034  3.42385227]
 [-3.41837115 -3.73350426 -2.03111284 -0.18796066  2.12088195  4.46150872]
 [-7.10674283 -7.93566487 -2.9043234  -0.3091886   2.86366403  4.53960253]]


In [8]:
np.save('BiLSTM_pred_np_6_summer.npy', average_pred)

Exception ignored in atexit callback: <bound method InteractiveShell.atexit_operations of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x2ae46fa39e70>>
Traceback (most recent call last):
  File "/home/csci8523/jiaxx215/.conda/envs/my_tensorflow_env/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3800, in atexit_operations
    self._atexit_once()
  File "/home/csci8523/jiaxx215/.conda/envs/my_tensorflow_env/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3783, in _atexit_once
    self.history_manager.end_session()
  File "/home/csci8523/jiaxx215/.conda/envs/my_tensorflow_env/lib/python3.10/site-packages/IPython/core/history.py", line 576, in end_session
    self.writeout_cache()
  File "/home/csci8523/jiaxx215/.conda/envs/my_tensorflow_env/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/csci8523/jiaxx215/.conda/envs/my_tensorflow_env/lib/python3.10/site-packages/IPyt