In [1]:
import numpy as np
import os

directory = "baseline_6"
cnt = 0
for filename in os.listdir(os.path.join(os.getcwd(), directory)):
#     print('hk')
    if cnt == 0:
#         print('in')
        loaded_np = np.load('baseline_6/' + filename)
        loaded_np = np.reshape(loaded_np, (1, loaded_np.shape[0], loaded_np.shape[1]))
        cnt += 1
    else:
        big_np = np.load('baseline_6/' + filename)
        big_np = np.reshape(big_np, (1, big_np.shape[0], big_np.shape[1]))


        # 12 x 8713 x 24 
        #concat
        loaded_np = np.concatenate((loaded_np, big_np), axis=0)
#         loaded_np = np.hstack((loaded_np, big_np))

        print(cnt)
        cnt += 1

    

1
2
3
4
5
6
7
8
9
10
11


In [2]:
print(loaded_np.shape)

(12, 8731, 6)


In [3]:
average_pred = np.mean(loaded_np, axis=0)
print(average_pred.shape)
print(average_pred)

(8731, 6)
[[73.21879784 74.54800891 75.89623131 77.24997224 78.61629111 80.01281106]
 [76.8681034  78.26466111 79.66774432 81.08443344 82.53237303 84.01742246]
 [80.4306034  81.87881041 83.34156341 84.83652653 86.36957917 87.9033204 ]
 ...
 [45.81433507 46.20630039 46.60122331 46.9574988  47.19098836 47.29392561]
 [45.46016841 45.83954692 46.17995414 46.39724485 46.48364579 46.35830508]
 [45.14072396 45.46657238 45.66900097 45.74023016 45.59940162 45.42265304]]


In [4]:
np.save('average_baseline_6.npy', average_pred)